openapi: 3.1.0

info:
    title: Movie Ticket Booking API
    summary: Rest API for Booking movie tickets
    description:   This API enables customers to browse movies, search theatres, reserve seats, complete payments, and download tickets. It also exposes administrative APIs for theatre operators.
    version: 1.0.0
    termsOfService: https://developer.moviebooking.com/terms
    contact: 
        name: Nilesh Kumar
        email: nk98943@gmail.com
        url: https://developer.moviebooking.com
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0

servers:
    - url: https://{environment}.moviebooking.com/
      variables:
        environment:
            default: dev-api
            enum:
                - dev-api
                - qa-api
                - api
        version:
            default: v1
            enum:
                - v1
                - v2
tags:
  - name: Authentication
    description: Login and registration

  - name: Movies
    description: Movie catalog


  - name: Theatres
    description: Theatre operations

  - name: Shows
    description: Movie show timings

  - name: Bookings
    description: Booking management

  - name: Payments
    description: Payment processing

  - name: Users
    description: User profile

  - name: Admin
    description: Administrative APIs

externalDocs:
    description: Developer Guide
    url: https://developer.moviebooking.com/docs

components:
    securitySchemes:
        OAuth2:
            type: oauth2
            description: OAuth2 Authorization Code Flow
            flows:
                authorizationCode:
                    authorizationUrl: https://auth.moviebooking.com/oauth/authorize
                    tokenUrl: https://auth.moviebooking.com/oauth/token
                    refreshUrl: https://auth.moviebooking.com/oauth/refresh
                    scopes:
                        movie.read: Read movies
                        movie.write: Manage movies
                        booking.read: Read bookings
                        booking.write: Create bookings
                        payment.process: Process payments
                        admin: Administrator access
        # OpenIDConnect:
        #     type: openIdConnect
        #     openIdConnectUrl: https://auth.moviebooking.com/.well-known/openid-configuration

        # BearerAuth:
        #     type: http
        #     scheme: bearer
        #     bearerFormat: JWT

        # ApiKey:
        #     type: apiKey
        #     in: header
        #     name: X-API-Key

        # CookieAuth:
        #     type: apiKey
        #     in: cookie
        #     name: SESSIONID 

    schemas:
        Movie:
            type: object
            description: Movie Information
            properties:
                movieId:
                    type: string
                    examples: ABCD1234
                title: 
                    type: string
                    examples: Avengers Endgame
                language:
                    type: string
                    example: English
                duration:
                    type: integer
                    example: 180
                genre:
                    type: array
                    items:
                        type: string
                        example:
                        - Action
                        - Adventure
                releaseDate:
                    type: string
                    format: date
                rating:
                    type: number
                    format: float
                    example: 8.9
            required:
                - movieId
                - title

        Booking:
            type: object
            description: Booking Details
            properties:
                bookingId:
                    type: string
                    example: Booking1001
                bookingStatus: 
                    type: array
                    items:
                        type: string
                        example:
                            - Confirmed
                            - Cancelled
                            - Pending
                totalAmount:
                    type: float
                    example: 450.50
                seats:
                    type: array
                    items:
                        $ref: '#/components/schemas/Seat'
        Seat:
            type: object
            description: Seat Details
            properties: 
                row:
                    type: string
                    example: A
                number:
                    type: number
                    example: 7
                type:
                    type: string
                    enum:
                        - Regular
                        - Premium
                        - Recliner
                price:
                    type: float
                    example: 250.80

        LoginRequestV1:
            type: object
            description: Login Details
            properties:
                email: 
                    type: string
                    example: nilesh@example.com
                password: 
                    type: string
                    example: Password@123
                rememberMe:
                    type: string
                    example: true
        LoginRequestV2:
            type: object
            description: Login Details
            properties:
                email: 
                    type: string
                    example: nilesh@example.com
                password: 
                    type: string
                    example: Password@123
                rememberMe:
                    type: string
                    example: true
                userType:
                    type: string
                    example: enterprise
        LoginResponse:
            type: object
            description: Bad request error responses
            properties:
                status:
                    type: integer
                    description: HTTP status code.
                    example: 400
        
        
        ErrorResponse:
            type: object
            description: Bad request error responses
            properties:
                status:
                    type: integer
                    description: HTTP status code.
                    example: 400
                error:
                    type: string
                    description: Short name of the HTTP error.
                    example: Bad Request
                code:
                    type: string
                    description: Application-specific error code.
                    example: INVALID_REQUEST

                message:
                    type: string
                    description: Human-readable explanation of the error.
                    example: The request contains invalid or missing fields.

                path:
                    type: string
                    description: API endpoint where the error occurred.
                    example: /movies
                traceId:
                    type: string
                    description: Unique identifier used for request tracing.
                    example: c5f74d2a-2b91-4e9b-aec5-8aabfbe53121
    responses:
        BadRequest:
            description: Invalid request
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/ErrorResponse'
        Unauthorized:
            description: Authentication failed
        NotFound:
            description: Resource not found
        InternalServerError:
            description: Unexpected server error
        
    parameters:
        MovieId:
            name: movieId
            in: path
            required: true
            description: Unique movie idetifier
            schema:
                type: string
                example: Movie1001
        City:
            name: city
            in: query   
            required: false
            schema:
                type: string
                example: Bengaluru
        Language:
            name: language
            in: query
            schema:
                type: string

    requestBodies:
        CreateBookings:
            description: Booking request
            required: true
            content:
                application/json:
                    schema:
                        type: object
                        properties:
                            showId:
                                type: string
                                example: SHOW1001
                            seats: 
                                type: array
                                items:
                                    type: string
                            paymentMethod:
                                type: string
    headers:
        X-Request-ID:
            description: Unique request identifier
            schema:
                type: string

        X-RateLimit-Remaining:
            description: Remaining API requests
            schema:
                type: integer

    examples:
        MovieExample:
            summary: Sample movie
            value:
                movieId: MOV123
                title: Avengers Endgame
                language: English
                duration: 180
        BookingExample:
            summary: Successful Booking
            value:
                bookingId: BKG123
                bookingStatus: CONFIRMED
                totalAmount: 750
        CustomerRegistrationExample:
            summary: Customer Registration Sample
            value: 
                firstName: Nilesh
                lastName: Kumar
                email: nilesh@example.com
                mobileNumber: "9876543210"
                password: Password@123
                confirmPassword: Password@123
                city: Bengaluru
                acceptTerms: true
        
    links:
        GetBookingDetails:
            operationId: getBookingById
            parameters:
                bookingId: '$response.body#/bookingId'
            description: Retrieve booking details

    callbacks:
        PaymentStatus:
            '{$request.body#/callbackUrl}':
            post:
                requestBody:
                    required: true
                    content:
                        application/json:
                        schema:
                            type: object
                            properties:
                            paymentId:
                                type: string
                            status:
                                type: string

                responses:
                    '200':
                        description: Callback received
    pathItems:
        MovieById:
        get:
            summary: Get Movie Details
            operationId: getMovieById
            responses:
            '200':
                description: Success

paths:
    /movies:
        get:
            tags:
                - Movies
            summary: Get all list of movies
            description:  Retrieves all movies currently available for booking. Users can optionally filter by language, genre, city, release status, and pagination.
            operationId: getMovies

            parameters:
                - $ref: '#/components/parameters/City'
                - name: language
                  in: query
                  description: Filter movies by language
                  required: false
                  schema:
                        type: string
                        example: English
                - name: genre
                  in: query
                  schema:
                    type: string
                    example: Action

                - name: page
                  in: query
                  schema:
                    type: integer
                    default: 1
                - name: size
                  in: query
                  schema:
                    type: integer
                    default: 20
            
            responses:
                '200':
                    description: Movies retrieved successfully
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                $ref: '#/components/schemas/Movie'

                '400':
                    $ref: '#/components/responses/BadRequest'

                '500':
                    $ref: '#/components/responses/InternalServerError'
    
    /movies/{movieId}:
        get:
            tags:
                - Movies
            summary: Get movie details
            description: Returns complete information for a movie.
            operationId: getMovieById
            parameters:
                - $ref: '#/components/parameters/MovieId'
            responses:
                '200':
                description: Movie details returned successfully
                content:
                    application/json:
                    schema:
                        $ref: '#/components/schemas/Movie'
                '404':
                $ref: '#/components/responses/NotFound'

    /theatres:
        get:
            tags:
                - Theatres
            summary: Search theatres
            operationId: searchTheatres
            parameters:
                - name: city
                  in: query
                  schema:
                    type: string

                - name: movieId
                  in: query
                  schema:
                    type: string

            responses:
                '200':
                    description: List of theatres
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                $ref: '#/components/schemas/Theatre'

    /auth/register:
        post:
            tags:
                - Authentication
            summary: Register a new user
            description: |
                Registers a new customer account for the Movie Ticket Booking platform.
                The API validates the request, checks for duplicate email/mobile number,
                securely hashes the password, creates the user account, and returns the
                registration details. Email or mobile verification can be completed
                through a separate verification API.
            operationId: registerUser
            security: []
            parameters:
                - name: X-Client-Id
                  in: header
                  required: true
                  description: Unique identifier of the client application.
                  schema:
                    type: string
                    example: movie-app-web
                - name: X-Correlation-Id
                  in: header
                  required: false
                  description: Unique request identifier used for tracing.
                  schema:
                    type: string
                    example: c5f74d2a-2b91-4e9b-aec5-8aabfbe53121

            requestBody:
                required: true
                description: Registration details of the customer.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequest'
                            # examples:
                            #     $ref: '#/components/examples/CustomerRegistrationExample'
                            CustomerRegistration:
                                summary: Register new customer
                                value:
                                    firstName: Nilesh
                                    lastName: Kumar
                                    email: nilesh@example.com
                                    mobileNumber: "9876543210"
                                    password: Password@123
                                    confirmPassword: Password@123
                                    city: Bengaluru
                                    acceptTerms: true

            responses:

                '201':
                    description: User registered successfully.
                    headers:
                        Location:
                            description: URI of the newly created user.
                            schema:
                                type: string
                                example: /users/USR10001

                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RegisterResponse'

                '400':
                    $ref: '#/components/responses/BadRequest'

                '409':
                    $ref: '#/components/responses/Conflict'

                '500':
                    $ref: '#/components/responses/InternalServerError'

    /v1/auth/login:
        post:
            tags:
                - Authentication
            summary: Authenticate user
            description: Authenticates a registered customer using email and password. On successful authentication the API returns an access token, refresh token, token expiration time, and user information.
            operationId: loginUser
            deprecated: true
            security: []
            parameters:
                - name: X-Client-Id
                  in: header
                  required: true
                  description: Unique client application identifier.
                  schema:
                    type: string
                    example: movie-app-web

                - name: X-Device-Id
                  in: header
                  required: false
                  description: Device identifier used for security auditing.
                  schema:
                    type: string
                    example: DEVICE-001

            requestBody:
                required: true
                description: Customer login credentials.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestV1'
            responses:
                '200':
                    description: Login successful.
                    headers:
                        X-Access-Token-Expires:
                            description: Token expiry time in seconds.
                            schema:
                                type: integer
                                example: 3600
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/LoginResponse'

                '400':
                    $ref: '#/components/responses/BadRequest'

                '401':
                    description: Invalid username or password.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '403':
                    description: Email verification pending.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '423':
                    description: User account is locked.
                    content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ErrorResponse'
                '500':
                    $ref: '#/components/responses/InternalServerError'

    /v2/auth/login:
        post:
            tags:
                - Authentication
            summary: Authenticate user
            description: Authenticates a registered customer using email and password. On successful authentication the API returns an access token, refresh token, token expiration time, and user information.
            operationId: loginUserV2
            security: []
            # parameters:
            #     - name: X-Client-Id
            #       in: header
            #       required: true
            #       description: Unique client application identifier.
            #       schema:
            #         type: string
            #         example: movie-app-web

            #     - name: X-Device-Id
            #       in: header
            #       required: false
            #       description: Device identifier used for security auditing.
            #       schema:
            #         type: string
            #         example: DEVICE-001

            requestBody:
                required: true
                description: Customer login credentials.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestV2'
            responses:
                '200':
                    description: Login successful.
                    headers:
                        X-Access-Token-Expires:
                            description: Token expiry time in seconds.
                                schema:
                                    type: integer
                                    example: 3600
                                    content:
                                        application/json:
                                            schema:
                                                $ref: '#/components/schemas/LoginResponse'

                '400':
                    $ref: '#/components/responses/BadRequest'

                '401':
                    description: Invalid username or password.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '403':
                    description: Email verification pending.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'

                '423':
                    description: User account is locked.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorResponse'
                '500':
                    $ref: '#/components/responses/InternalServerError'